id: PA10ED161
initial_creation_type: input
source_metadata:
  Title: Pratityasamutpada hrdaya and Dharmadhatugarbhavivarana
  Editor: Gyaltsen Namdrol
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '1997'
  Āryadharmadhātugarbhavivaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:18:01.234341'
last_modified_at: '2022-03-08T16:18:01.234349'
